apiVersion: v1
kind: Namespace
metadata:
  name: camille
---
apiVersion: v1
kind: Service
metadata:
  name: training
  namespace: camille
spec:
  selector:
    app: training
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  namespace: camille
  labels:
    app: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: pytorch/pytorch-binary-docker-image-ubuntu16.04:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired
        - resourceName: memory
          restartPolicy: NotRequired
        resources:
          limits:
            memory: "3200Mi"
            cpu: "12000m"
          requests:
            memory: "3200Mi"
            cpu: "12000m"
