apiVersion: v1
kind: Service
metadata:
  name: training
  namespace: camille-training
spec:
  selector:
    app: training
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: training
  namespace: camille-training
  labels:
    app: training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training
  template:
    metadata:
      labels:
        app: training
    spec:
      containers:
      - name: training
        image: public.ecr.aws/e9o7l9v1/w210-second-sight-model-training:latest
        ports:
          - containerPort: 8080
